export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_ITEM_CART = 'REMOVE_ITEM_CART';
export const SAVE_SHIPPING_INFO = 'SAVE_SHIPPING_INFO';
export const SAVE_TO_STORAGE = 'SAVE_TO_CART';
export const REMOVE_FROM_STORAGE = 'REMOVE_FROM_STORAGE';
export const EMPTY_CART = 'EMPTY_CART';
